export const AUTH_STABILIZATION_PERSIAN: Record<string, string> = {
  "Enter your signup email to request a new verification link.": "برای دریافت لینک تأیید جدید، ایمیلی را که با آن ثبت‌نام کرده‌اید وارد کنید.",
  Username: "نام کاربری",
  "Username or email": "نام کاربری یا ایمیل",
  "Enter your username or email.": "نام کاربری یا ایمیل خود را وارد کنید.",
  "Enter a valid username or email.": "یک نام کاربری یا ایمیل معتبر وارد کنید.",
  "Use 6–30 lowercase English letters, numbers, or underscores.": "نام کاربری باید ۶ تا ۳۰ کاراکتر و فقط شامل حروف انگلیسی کوچک، عدد یا زیرخط باشد.",
  "Username is already taken.": "این نام کاربری قبلاً انتخاب شده است.",
  "This account already exists. Sign in instead.": "این حساب قبلاً ساخته شده است. وارد حساب شوید.",
  "Email or password is incorrect.": "ایمیل یا رمز عبور نادرست است.",
  "Your email is not verified yet. Check the verification email from sign up.": "ایمیل شما هنوز تأیید نشده است. ایمیل تأییدی را که هنگام ثبت‌نام ارسال شد بررسی کنید.",
  "Sign in with your username or email.": "با نام کاربری یا ایمیل خود وارد شوید.",
  "Email verified. Sign in to continue in AgroMind.": "ایمیل تأیید شد. برای ادامه در AgroMind وارد حساب شوید.",
  "Check your inbox at": "صندوق ورودی این ایمیل را بررسی کنید:",
  "Open the verification email, verify your address, then return to the AgroMind app.": "ایمیل تأیید را باز کنید، آدرس ایمیل را تأیید کنید و سپس به اپ AgroMind برگردید.",
  "Checking verification status…": "در حال بررسی وضعیت تأیید…",
  "Verification email sent. Check your inbox and spam folder.": "ایمیل تأیید ارسال شد. صندوق ورودی و پوشه هرزنامه را بررسی کنید.",
  "Verification is available after you create an account.": "تأیید ایمیل فقط پس از ساخت حساب در دسترس است.",
  "Return to the AgroMind app to continue.": "برای ادامه به اپ AgroMind برگردید.",
  "You can close this browser tab now.": "اکنون می‌توانید این صفحه مرورگر را ببندید.",
  "Back to sign up": "بازگشت به ثبت‌نام",
  "Create an account": "ساخت حساب",
  "Your name": "نام و نام خانوادگی",
  "Tell us your name to personalize your AgroMind account.": "برای شخصی‌سازی حساب AgroMind، نام و نام خانوادگی خود را وارد کنید.",
  "Enter your first and last name.": "نام و نام خانوادگی خود را کامل وارد کنید.",
  "Verify your email to continue setting up your AgroMind account.": "برای ادامه راه‌اندازی حساب AgroMind، ایمیل خود را تأیید کنید.",
  "Use my location": "استفاده از موقعیت من",
  "Finding your region…": "در حال پیدا کردن منطقه شما…",
  "Location could not determine your region. Choose it manually.": "موقعیت مکانی نتوانست منطقه شما را تشخیص دهد. آن را دستی انتخاب کنید.",
};
