export const COMMON_PERSIAN: Record<string, string> = {
  "Live field intelligence": "هوشمندی زنده مزرعه",
  "Hyper-local weather": "هواشناسی دقیق محلی",
  "Smarter water use": "مصرف هوشمندتر آب",
  "Actionable AI": "هوش مصنوعی کاربردی",
  "Live overview": "نمای زنده",
  "All systems online": "همه سامانه‌ها فعال‌اند",
  "Clear skies": "آسمان صاف",
  "Soil moisture": "رطوبت خاک",
  "In target range": "در محدوده هدف",
  "Starts at {time}": "شروع در {time}",
  "Crop health": "سلامت محصول",
  "Stable": "پایدار",
  "Moisture trend": "روند رطوبت",
  "Last 24 hours": "۲۴ ساعت گذشته",
  "AI recommendation": "پیشنهاد هوش مصنوعی",
  "Delay irrigation until evening to reduce evaporation.": "برای کاهش تبخیر، آبیاری را تا عصر به تعویق بیندازید.",
  "Connected intelligence": "هوشمندی یکپارچه",
  "One farm. One intelligent system.": "یک مزرعه؛ یک سامانه هوشمند.",
  "AgroMind connects field signals, local weather and irrigation into one clear operating picture—then helps you act on it.": "AgroMind داده‌های مزرعه، هواشناسی محلی و آبیاری را در یک نمای عملیاتی روشن یکپارچه می‌کند و برای اقدام بعدی راهنمایتان است.",
  "Read the field": "دریافت داده مزرعه",
  "Understand conditions": "درک شرایط",
  "Control every drop": "کنترل هر قطره",
  "AI": "هوش مصنوعی",
  "Turn data into action": "تبدیل داده به اقدام",
  "Farmer": "کشاورز",
  "Decide with confidence": "تصمیم‌گیری مطمئن",
  "Built around the work": "طراحی‌شده برای کار واقعی",
  "From forecast to field action.": "از پیش‌بینی تا اقدام در مزرعه.",
  "Four connected capabilities, designed as one agricultural workflow—not a collection of disconnected tools.": "چهار قابلیت متصل در قالب یک گردش کار کشاورزی؛ نه مجموعه‌ای از ابزارهای جدا از هم.",
  "Know what is coming to every field.": "بدانید در هر مزرعه چه شرایطی در راه است.",
  "Live conditions, rainfall timing and farm-local forecasts turn weather into practical field decisions.": "شرایط لحظه‌ای، زمان بارش و پیش‌بینی محلی، هواشناسی را به تصمیم‌های عملی مزرعه تبدیل می‌کنند.",
  "Water with timing, context and control.": "آبیاری با زمان‌بندی، شناخت و کنترل.",
  "Coordinate schedules, soil moisture and weather signals before every irrigation cycle.": "پیش از هر نوبت آبیاری، برنامه، رطوبت خاک و شرایط هوا را هماهنگ کنید.",
  "Keep every farm, garden and crop in view.": "همه مزرعه‌ها، باغ‌ها و محصولات را زیر نظر داشته باشید.",
  "Organize locations, growing areas, crops and field activity without losing the operational picture.": "موقعیت‌ها، زمین‌های کشت، محصولات و فعالیت‌ها را بدون از دست دادن نمای عملیاتی مدیریت کنید.",
  "AI Recommendations": "پیشنهادهای هوش مصنوعی",
  "Move from raw signals to the next best action.": "از داده خام به بهترین اقدام بعدی برسید.",
  "AgroMind turns connected farm data into concise, explainable recommendations you can review and act on.": "AgroMind داده‌های متصل مزرعه را به پیشنهادهای کوتاه و قابل توضیح برای بررسی و اقدام تبدیل می‌کند.",
  "Designed for real field decisions": "برای تصمیم‌های واقعی مزرعه طراحی شده",
  "Local conditions": "شرایط محلی",
  "Rain arriving this evening": "بارش در راه عصر امروز",
  "Tonight": "امشب",
  "Ready to irrigate": "آماده آبیاری",
  "Weather check complete": "بررسی هوا تکمیل شد",
  "Next schedule": "برنامه بعدی",
  "Irrigation zone": "ناحیه آبیاری",
  "Zone 2": "ناحیه ۲",
  "Farm map": "نقشه مزرعه",
  "North field": "زمین شمالی",
  "Corn · Active": "ذرت · فعال",
  "Walnut garden": "باغ گردو",
  "Healthy": "سالم",
  "AgroMind insight": "بینش AgroMind",
  "Based on connected farm data": "بر اساس داده‌های متصل مزرعه",
  "Rain probability {value}": "احتمال بارش {value}",
  "Moisture stable": "رطوبت پایدار",
  "Confidence": "اطمینان",
  "Live farm overview": "نمای زنده مزرعه",
  "Your farm never stands still.": "مزرعه شما هرگز متوقف نمی‌شود.",
  "See weather, water, crops and recommendations update together in one operational view.": "تغییرات هوا، آب، محصول و پیشنهادها را هم‌زمان در یک نمای عملیاتی ببینید.",
  "Sample operational data": "داده عملیاتی نمونه",
  "Current weather": "هوای فعلی",
  "Clear · light wind": "صاف · باد ملایم",
  "Target {low}–{high}": "هدف {low} تا {high}",
  "Irrigation state": "وضعیت آبیاری",
  "Ready": "آماده",
  "Next cycle {time}": "نوبت بعدی {time}",
  "Stable this week": "این هفته پایدار",
  "AI insight": "بینش هوش مصنوعی",
  "Hold irrigation until evening": "آبیاری را تا عصر متوقف کنید",
  "Lower evaporation expected after sunset": "پس از غروب تبخیر کمتری انتظار می‌رود",
  "Install AgroMind": "نصب AgroMind",
  "Add AgroMind to your home screen for faster access and a focused, app-like experience.": "AgroMind را برای دسترسی سریع‌تر و تجربه‌ای شبیه اپ به صفحه اصلی دستگاه اضافه کنید.",
  "Use your browser menu to add AgroMind to your home screen.": "از منوی مرورگر، AgroMind را به صفحه اصلی اضافه کنید.",
  "AgroMind is ready on your home screen.": "AgroMind روی صفحه اصلی شما آماده است.",
  "You can install AgroMind whenever you are ready.": "هر زمان آماده بودید می‌توانید AgroMind را نصب کنید.",
  "Ready to run your farm smarter?": "آماده‌اید مزرعه را هوشمندتر مدیریت کنید؟",
  "Bring every field decision into one calm, connected workspace.": "همه تصمیم‌های مزرعه را در یک فضای یکپارچه و ساده مدیریت کنید.",
  "Enter AgroMind": "ورود به AgroMind",
  "System": "سامانه",
  "Live farm": "مزرعه زنده",
  "Smart Farming, Smarter Future": "کشاورزی هوشمند، آینده‌ای هوشمندتر",
  "English": "انگلیسی",
  "Persian · right to left": "فارسی · راست به چپ",
  "{theme} theme": "پوسته {theme}",
  "{day} forecast": "پیش‌بینی {day}",
  "{label}, {period}, {temperature}, {condition}. Open details": "{label}، {period}، {temperature}، {condition}. باز کردن جزئیات",
  "{day}, {condition}, low {low}, high {high}, forecast precipitation {rain}. Open daily details": "{day}، {condition}، کمینه {low}، بیشینه {high}، بارش پیش‌بینی‌شده {rain}. باز کردن جزئیات روزانه",
  "Offline. Showing the last received report.": "آفلاین هستید. آخرین گزارش دریافت‌شده نمایش داده می‌شود.",
  "You are offline. Reconnect to load weather.": "آفلاین هستید. برای دریافت هواشناسی دوباره متصل شوید.",
  "Could not refresh. Showing the last received report.": "به‌روزرسانی انجام نشد. آخرین گزارش دریافت‌شده نمایش داده می‌شود.",
  "Unable to load weather data. Please try again.": "داده‌های هواشناسی بارگیری نشد. دوباره تلاش کنید.",
  "North": "شمال", "North-northeast": "شمال-شمال‌شرقی", "Northeast": "شمال‌شرقی", "East-northeast": "شرق-شمال‌شرقی",
  "East": "شرق", "East-southeast": "شرق-جنوب‌شرقی", "Southeast": "جنوب‌شرقی", "South-southeast": "جنوب-جنوب‌شرقی",
  "South": "جنوب", "South-southwest": "جنوب-جنوب‌غربی", "Southwest": "جنوب‌غربی", "West-southwest": "غرب-جنوب‌غربی",
  "West": "غرب", "West-northwest": "غرب-شمال‌غربی", "Northwest": "شمال‌غربی", "North-northwest": "شمال-شمال‌غربی",
  "Location": "موقعیت", "Make AgroMind more local": "AgroMind را محلی‌تر کنید", "Allow location access to personalize your region, dates, weather, and local information.": "برای تنظیم منطقه، تاریخ، هواشناسی و اطلاعات محلی، دسترسی موقعیت را فعال کنید.", "Not now": "فعلاً نه", "Detecting...": "در حال شناسایی…", "Allow Location": "اجازه دسترسی به موقعیت",
  ". All rights reserved.": "؛ تمامی حقوق محفوظ است.", ". Create a schedule below when you are ready.": "؛ می‌توانید برنامه آبیاری را در ادامه تنظیم کنید.",
  "? All information associated with this": "؟ تمام اطلاعات مربوط به این", "A unique name is required for every farm or garden.": "نام هر مزرعه یا باغ باید یکتا باشد.",
  "AI Insights": "تحلیل هوش مصنوعی", "AI analysis is not available yet": "تحلیل هوش مصنوعی هنوز در دسترس نیست",
  "AI-Powered Precision Agriculture": "کشاورزی دقیق با هوش مصنوعی", "Active Property": "زمین انتخاب‌شده", "Active farm": "مزرعه انتخاب‌شده",
  "Add": "افزودن", "Add Farm / Garden": "افزودن مزرعه یا باغ", "Add New": "افزودن", "Add Plant / Tree": "افزودن گیاه یا درخت",
  "Add a farm first": "ابتدا یک مزرعه اضافه کنید", "Add a farm or garden": "افزودن مزرعه یا باغ",
  "Add a farm or garden to start monitoring weather, irrigation, field conditions, and future AI insights.": "با افزودن مزرعه یا باغ، پایش هواشناسی، آبیاری و شرایط زمین را شروع کنید.",
  "Add a farm or garden with its exact location to see local conditions and forecasts.": "مزرعه یا باغ را با موقعیت دقیق اضافه کنید تا شرایط و پیش‌بینی محلی نمایش داده شود.",
  "Add a general location or select the exact position on the map.": "نام محل را وارد کنید یا موقعیت دقیق را روی نقشه انتخاب کنید.",
  "Add a location for": "افزودن موقعیت برای", "Add farm location": "افزودن موقعیت مزرعه", "Add the basic information about your": "اطلاعات پایه را وارد کنید:",
  "Add the details for this plant type.": "جزئیات این نوع گیاه را وارد کنید.",
  "Add the exact farm location to enable live weather data for this property.": "برای دریافت هواشناسی، موقعیت دقیق مزرعه را اضافه کنید.",
  "Add the main crop grown on this farm.": "محصول اصلی این مزرعه را وارد کنید.",
  "Add the plants or trees managed in this garden.": "گیاهان یا درخت‌های این باغ را اضافه کنید.",
  "Add the tree or plant types you grow in this garden.": "نوع درخت‌ها یا گیاهان این باغ را اضافه کنید.",
  "Add up to 5 types of trees or plants in this garden.": "تا ۵ نوع درخت یا گیاه برای این باغ اضافه کنید.",
  "Add your first farm or garden to start managing irrigation, crops, weather, and AI recommendations.": "برای مدیریت آبیاری، محصولات و هواشناسی، اولین مزرعه یا باغ خود را اضافه کنید.",
  "Add your information step by step.": "اطلاعات را مرحله‌به‌مرحله وارد کنید.", "Age": "سن", "AgroMind AI": "هوش مصنوعی AgroMind",
  "AgroMind combines weather intelligence, irrigation management, AI recommendations, GPS mapping and crop planning into one powerful farming platform.": "AgroMind هواشناسی، مدیریت آبیاری، پیشنهادهای هوش مصنوعی، نقشه زمین و برنامه‌ریزی کشت را در یک برنامه جمع می‌کند.",
  "AgroMind has not received any field sensor data for this property yet.": "هنوز داده‌ای از حسگرهای این زمین دریافت نشده است.",
  "Are you sure you want to permanently delete": "از حذف دائمی این مورد مطمئن هستید؟",
  "Area": "مساحت", "Back to": "بازگشت به", "Back to Farms": "بازگشت به مزرعه‌ها", "Calculate from dimensions": "محاسبه از روی ابعاد",
  "Cancel": "انصراف", "Chance": "احتمال", "Change the exact position of this property on the map.": "موقعیت دقیق این زمین را روی نقشه تغییر دهید.",
  "Check your information before creating it.": "پیش از ایجاد، اطلاعات را بررسی کنید.",
  "Checks every 5 minutes while this page is visible.": "تا زمانی که این صفحه باز است، هر ۵ دقیقه بررسی می‌شود.",
  "Checks every 5 minutes while visible. Last checked": "در حالت نمایش، هر ۵ دقیقه بررسی می‌شود. آخرین بررسی:",
  "Choose a new date and time to reschedule this irrigation.": "برای تغییر برنامه آبیاری، تاریخ و ساعت جدید انتخاب کنید.",
  "Choose how long the irrigation should run.": "مدت آبیاری را انتخاب کنید.", "Choose how this farm is irrigated.": "روش آبیاری مزرعه را انتخاب کنید.",
  "Choose irrigation time": "انتخاب ساعت آبیاری", "Choose irrigation date": "انتخاب تاریخ آبیاری",
  "Choose the type of land you want to manage with AgroMind.": "نوع زمینی را که می‌خواهید مدیریت کنید انتخاب کنید.",
  "Click on the map to place the exact location.": "برای تعیین موقعیت دقیق روی نقشه بزنید.", "Confirm Delete": "تأیید حذف",
  "Control and schedule irrigation.": "کنترل و برنامه‌ریزی آبیاری.", "Control irrigation for": "کنترل آبیاری برای",
  "Create": "ایجاد", "Crop": "محصول", "Current irrigation plan": "برنامه فعلی آبیاری", "Current schedule for the active property.": "برنامه فعلی زمین انتخاب‌شده.",
  "Daily sunrise, sunset and daylight at this farm": "طلوع، غروب و طول روز در این مزرعه", "Day": "روز", "Daylight duration ·": "طول روز ·",
  "Delete": "حذف", "Detailed information about this": "اطلاعات کامل", "Discard Changes": "کنار گذاشتن تغییرات", "Done": "انجام شد", "Duration": "مدت",
  "Each hourly timestamp marks the end of the preceding hour's precipitation amount.": "هر ساعت، پایان بازه یک‌ساعته بارش قبل از آن را نشان می‌دهد.",
  "Edit": "ویرایش", "Edit Property": "ویرایش زمین", "Enter area": "ورود مساحت", "Enter the area directly or calculate it from the dimensions.": "مساحت را وارد کنید یا از روی ابعاد به دست آورید.",
  "Enter the total area directly.": "مساحت کل را مستقیم وارد کنید.", "Estimated Area": "مساحت محاسبه‌شده", "Estimated Water Usage": "مصرف آب تخمینی",
  "Everything your farm needs,": "هرآنچه مزرعه شما نیاز دارد،", "Exact Location": "موقعیت دقیق", "Farm Dashboard": "داشبورد مزرعه",
  "Farm Details": "جزئیات مزرعه", "Farm Management": "مدیریت مزرعه", "Farm Overview": "نمای کلی مزرعه",
  "Farm location is not configured": "موقعیت مزرعه تعیین نشده است", "Farm not found": "مزرعه پیدا نشد",
  "Feels": "احساس", "Feels like": "دمای احساسی", "Field monitoring": "پایش مزرعه",
  "Fix the validation errors before saving. You can still discard the changes.": "پیش از ذخیره، خطاهای ورودی را برطرف کنید. می‌توانید تغییرات را کنار بگذارید.",
  "For agricultural land used for crops and larger-scale farming.": "برای زمین‌های زراعی و کشت در مقیاس بزرگ‌تر.",
  "For gardens, orchards, and smaller cultivated areas.": "برای باغ‌ها، باغچه‌ها و زمین‌های کوچک‌تر.",
  "Forecast hour": "ساعت پیش‌بینی", "Forecast totals are estimates. Measured daily rainfall requires local observations.": "مجموع پیش‌بینی‌ها تخمینی است؛ بارش اندازه‌گیری‌شده روزانه به مشاهدات محلی نیاز دارد.",
  "Forecast unavailable": "پیش‌بینی در دسترس نیست", "From": "از", "Full-day forecast ·": "پیش‌بینی کل روز ·",
  "Future insights will combine farm information, irrigation activity, sensor readings, weather data, and crop conditions before giving recommendations.": "تحلیل‌های آینده اطلاعات مزرعه، فعالیت آبیاری، حسگرها، هواشناسی و شرایط محصول را برای ارائه پیشنهاد ترکیب می‌کنند.",
  "Garden / Orchard": "باغ یا باغچه", "Hour": "ساعت", "Hourly Forecast": "پیش‌بینی ساعتی",
  "Hourly air-temperature samples; not a ground-frost observation.": "نمونه‌های ساعتی دمای هوا؛ متفاوت با مشاهده یخ‌زدگی سطح زمین.",
  "Includes available hours across midnight, until the next daylight forecast.": "شامل ساعت‌های موجود در دو سوی نیمه‌شب تا آغاز روز بعد است.",
  "Intelligent recommendations for": "پیشنهادهای هوشمند برای", "Irrigation Control": "کنترل آبیاری", "Irrigation Duration": "مدت آبیاری",
  "Irrigation Management": "مدیریت آبیاری", "Irrigation Overview": "نمای کلی آبیاری", "Irrigation Schedule": "برنامه آبیاری", "Irrigation Type": "روش آبیاری",
  "Irrigation cannot be scheduled for a time that has already passed.": "زمان آبیاری نمی‌تواند در گذشته باشد.", "Irrigation duration": "مدت آبیاری",
  "Irrigation for": "آبیاری برای", "Irrigation method": "روش آبیاری",
  "Irrigation settings, schedules, sensors, and automation are connected to individual farms and gardens.": "تنظیمات، برنامه‌ها، حسگرها و خودکارسازی آبیاری برای هر مزرعه و باغ جداگانه‌اند.",
  "Irrigation types": "روش‌های آبیاری", "Jump directly to the most common farm management tasks.": "دسترسی سریع به کارهای اصلی مدیریت مزرعه.",
  "Latest": "آخرین", "Latest available weather for this farm location.": "آخرین داده هواشناسی موجود برای موقعیت این مزرعه.",
  "Length": "طول", "Live": "زنده", "Live sensor status for": "وضعیت زنده حسگرها برای", "Loading chart…": "در حال بارگذاری نمودار…",
  "Loading local weather…": "در حال دریافت هواشناسی محلی…", "Loading map...": "در حال بارگذاری نقشه…", "Loading weather data...": "در حال دریافت هواشناسی…",
  "Local time": "وقت محلی", "Manage Irrigation": "مدیریت آبیاری", "Manage active property": "مدیریت زمین انتخاب‌شده",
  "Manage irrigation": "مدیریت آبیاری", "Manage the plants and trees in this garden.": "گیاهان و درخت‌های این باغ را مدیریت کنید.",
  "Manage your farms and gardens in one place.": "مزرعه‌ها و باغ‌های خود را یک‌جا مدیریت کنید.", "Measured daily total": "بارش روزانه اندازه‌گیری‌شده",
  "Minute": "دقیقه", "Model estimate ·": "برآورد مدل ·", "Monitor and manage irrigation for your farm.": "آبیاری مزرعه را پایش و مدیریت کنید.",
  "Monitor and manage irrigation for your farms and gardens.": "آبیاری مزرعه‌ها و باغ‌ها را پایش و مدیریت کنید.",
  "Monitor your farm conditions and make smarter decisions.": "شرایط مزرعه را پایش کنید و تصمیم‌های بهتری بگیرید.",
  "Monitor your farms, optimize irrigation, analyze weather and make better farming decisions with AI.": "مزرعه‌ها را پایش کنید، آبیاری را بهبود دهید و با تحلیل هواشناسی و هوش مصنوعی بهتر تصمیم بگیرید.",
  "More precise location = better weather data.": "موقعیت دقیق‌تر، داده هواشناسی مرتبط‌تری فراهم می‌کند.", "My Farms & Gardens": "مزرعه‌ها و باغ‌های من",
  "Name": "نام", "Next": "بعدی", "No": "هیچ", "No data": "بدون داده", "No farms or gardens yet": "هنوز مزرعه یا باغی اضافه نشده است",
  "No irrigation scheduled": "آبیاری برنامه‌ریزی نشده است", "No irrigation sensors are currently configured for this farm.": "حسگر آبیاری برای این مزرعه تنظیم نشده است.",
  "No plants added yet": "هنوز گیاهی اضافه نشده است", "No plants or trees added": "گیاه یا درختی اضافه نشده است",
  "No plants or trees have been added to this garden yet.": "هنوز گیاه یا درختی به این باغ اضافه نشده است.", "No plants specified": "گیاهی مشخص نشده است",
  "No rain-gauge observation is connected to this farm.": "داده باران‌سنج به این مزرعه متصل نیست.",
  "No sensors connected": "حسگری متصل نیست", "Not connected": "متصل نیست", "Now + next 24 hours ·": "اکنون و ۲۴ ساعت آینده ·",
  "Optimal": "مناسب", "Normal": "عادی", "Warning": "هشدار",
  "Optional. Leave this blank to detect the location name automatically from the map.": "اختیاری؛ با خالی گذاشتن، نام محل از نقشه تعیین می‌شود.",
  "Overview of the current irrigation status and upcoming plan.": "نمای کلی وضعیت فعلی و برنامه بعدی آبیاری.",
  "Place your farm on the map to load its weather.": "برای دریافت هواشناسی، موقعیت مزرعه را روی نقشه تعیین کنید.",
  "Plan the next irrigation session for": "برنامه نوبت بعدی آبیاری برای", "Plant / Tree": "گیاه یا درخت", "Plant / Tree Name": "نام گیاه یا درخت",
  "Plants & Trees": "گیاهان و درخت‌ها", "Plants / Trees": "گیاهان و درخت‌ها", "Plants and trees currently managed in this garden.": "گیاهان و درخت‌های این باغ.",
  "Please choose a future date and time.": "تاریخ و ساعتی در آینده انتخاب کنید.", "Previous": "قبلی", "Property Type": "نوع زمین", "Property type": "نوع زمین",
  "Quantity": "تعداد", "Quick Actions": "دسترسی سریع", "Ready to make smarter farming decisions?": "آماده‌اید تصمیم‌های بهتری برای مزرعه بگیرید؟",
  "Remote irrigation": "آبیاری از راه دور", "Reschedule Irrigation": "تغییر برنامه آبیاری", "Review": "بازبینی",
  "Save Location": "ذخیره موقعیت", "Save Schedule": "ذخیره برنامه", "Schedule irrigation": "برنامه‌ریزی آبیاری", "Schedule ready": "برنامه آماده است",
  "Select Farm Location": "انتخاب موقعیت مزرعه", "Select the exact farm position on the map. This is required for location-based AgroMind features.": "موقعیت دقیق مزرعه را روی نقشه انتخاب کنید؛ قابلیت‌های مکانی AgroMind به آن نیاز دارند.",
  "Selected": "انتخاب‌شده", "Selected Area": "مساحت انتخاب‌شده", "Selected coordinates": "مختصات انتخاب‌شده",
  "Sensor Status": "وضعیت حسگرها", "Set farm location": "تعیین موقعیت مزرعه",
  "Soil moisture and other field readings will appear here when compatible AgroMind sensors are connected.": "با اتصال حسگرهای سازگار، رطوبت خاک و دیگر داده‌های مزرعه اینجا نمایش داده می‌شوند.",
  "Source": "منبع", "Spacing": "فاصله کاشت", "Start Farming": "شروع مدیریت مزرعه", "Start Irrigation": "شروع آبیاری",
  "Start Time": "ساعت شروع", "Start with AgroMind": "شروع با AgroMind", "Start with your first farm": "از اولین مزرعه شروع کنید",
  "Status": "وضعیت", "Step": "مرحله", "Stop Irrigation": "توقف آبیاری", "Sunrise": "طلوع", "Sunrise / sunset unavailable": "طلوع و غروب در دسترس نیست", "Sunset": "غروب",
  "The extended forecast is temporarily unavailable. Showing": "پیش‌بینی بلندمدت موقتاً در دسترس نیست. نمایش",
  "The latest report is over 30 minutes old.": "بیش از ۳۰ دقیقه از آخرین گزارش گذشته است.",
  "The selected farm or garden does not exist.": "مزرعه یا باغ انتخاب‌شده وجود ندارد.",
  "There is currently no irrigation schedule for": "در حال حاضر برنامه آبیاری وجود ندارد برای",
  "There is currently no irrigation schedule for this property.": "در حال حاضر برنامه آبیاری برای این زمین وجود ندارد.",
  "This action cannot be undone.": "این کار قابل بازگشت نیست.", "This action requires confirmation.": "این کار به تأیید نیاز دارد.",
  "This irrigation schedule has passed.": "زمان این برنامه آبیاری گذشته است.",
  "This name is already being used. Please choose a different name.": "این نام قبلاً استفاده شده است؛ نام دیگری انتخاب کنید.",
  "This night spans two forecast providers. Lines stop at the provider change; each reading shows its source.": "پیش‌بینی این شب از دو منبع است. خط نمودار در مرز منابع قطع می‌شود و منبع هر مقدار مشخص است.",
  "This report is over 30 minutes old.": "بیش از ۳۰ دقیقه از این گزارش گذشته است.", "Today's forecast:": "پیش‌بینی امروز:",
  "Try again": "تلاش دوباره", "Type": "نوع", "Unavailable": "در دسترس نیست", "Unsaved Changes": "تغییرات ذخیره‌نشده",
  "Update location, crop, area, and settings.": "ویرایش موقعیت، محصول، مساحت و تنظیمات.", "Update the information for": "ویرایش اطلاعات",
  "Use current time": "استفاده از ساعت فعلی", "Use length and width.": "استفاده از طول و عرض.", "Use my location": "استفاده از موقعیت من",
  "Use the forecast hour slider or the data table below for exact values. Gaps mean unavailable data or a change of forecast provider.": "برای مقادیر دقیق از لغزنده ساعت یا جدول استفاده کنید. فاصله‌ها نشان‌دهنده نبود داده یا تغییر منبع پیش‌بینی‌اند.",
  "View Details": "مشاهده جزئیات", "View details": "مشاهده جزئیات", "View hourly values": "مشاهده مقادیر ساعتی", "View irrigation & sensors": "مشاهده آبیاری و حسگرها",
  "View property information and details.": "مشاهده اطلاعات و جزئیات زمین.", "Water Tank": "مخزن آب", "Weather data by": "داده هواشناسی از",
  "Weather for your field": "هواشناسی مزرعه شما", "Weather unavailable": "هواشناسی در دسترس نیست",
  "WeatherAPI is unavailable. Current conditions and forecasts are using Open-Meteo model data.": "WeatherAPI در دسترس نیست؛ شرایط فعلی و پیش‌بینی از مدل Open-Meteo دریافت می‌شوند.",
  "WeatherAPI unavailable. Current conditions and forecasts now use Open-Meteo.": "WeatherAPI در دسترس نیست؛ داده‌ها اکنون از Open-Meteo دریافت می‌شوند.",
  "What do you want to manage?": "چه نوع زمینی را می‌خواهید مدیریت کنید؟", "Why AgroMind": "چرا AgroMind؟", "Width": "عرض", "Wind": "باد",
  "You have unsaved changes. Do you want to save them before leaving this page?": "تغییرات ذخیره‌نشده دارید. پیش از خروج آن‌ها را ذخیره می‌کنید؟",
  "Your farms & gardens": "مزرعه‌ها و باغ‌های شما", "at": "در ساعت", "available days.": "روز موجود.", "for": "برای",
  "forecast is available for this day.": "پیش‌بینی برای این روز موجود نیست.", "forecast is temporarily unavailable.": "پیش‌بینی موقتاً در دسترس نیست.",
  "forecasts for": "پیش‌بینی برای", "in": "در", "in one intelligent platform.": "در یک برنامه هوشمند.", "is scheduled for": "برنامه‌ریزی شده برای",
  "min": "دقیقه", "minutes": "دقیقه", "of 5 plant types added": "نوع از ۵ نوع گیاه اضافه شده", "plants ·": "گیاه ·", "spacing ·": "فاصله کاشت ·",
  "when a compatible irrigation controller is connected.": "پس از اتصال کنترل‌کننده آبیاری سازگار.",
  "will appear here when the AgroMind AI engine is connected.": "پس از اتصال موتور هوش مصنوعی اینجا نمایش داده می‌شوند.",
  "will be removed from AgroMind.": "از AgroMind حذف خواهد شد.", "years old": "ساله", "yrs": "سال", "· All times are local to this farm.": "· تمام ساعت‌ها به وقت محلی مزرعه‌اند.",
  "· Checking…": "· در حال بررسی…", "· Earlier hours on this chart remain forecasts.": "· ساعت‌های گذشته این نمودار هم پیش‌بینی‌اند.", "· Hourly forecast ·": "· پیش‌بینی ساعتی ·",
  "Sample farm": "مزرعه نمونه", "Norfolk, United Kingdom": "نورفک، بریتانیا", "Your Farm Powered by Intelligence": "مدیریت هوشمند مزرعه شما",
  "Monitor your farms, optimize irrigation, analyze weather, and make smarter farming decisions with AI.": "مزرعه‌ها را پایش کنید، آبیاری را بهبود دهید و با تحلیل هواشناسی و هوش مصنوعی بهتر تصمیم بگیرید.",
  "Live Demo": "نمایش نمونه", "Irrigate in 6 hours": "آبیاری تا ۶ ساعت دیگر", "Features": "قابلیت‌ها", "About": "درباره ما", "Contact": "تماس",
  "Select a date": "انتخاب تاریخ", "Select a time": "انتخاب ساعت", "Previous month": "ماه قبل", "Next month": "ماه بعد",
  "Switch to PM": "تغییر به بعدازظهر", "Switch to AM": "تغییر به قبل‌ازظهر", "Increase hour": "افزایش ساعت", "Decrease hour": "کاهش ساعت",
  "Increase minute": "افزایش دقیقه", "Decrease minute": "کاهش دقیقه", "Gusts": "تندباد", "previous": "گذشته", "Rain chance": "احتمال باران",
  "Snow chance": "احتمال برف", "Precipitation chance": "احتمال بارش", "Night temperature": "دمای شب", "Cloud cover": "پوشش ابر",
  "Some hourly rainfall amounts are unavailable. Peak gusts reach {wind}.": "بعضی مقادیر بارش ساعتی در دسترس نیستند. بیشترین تندباد {wind} است.",
  "Forecast readings at or below {value}": "مقادیر پیش‌بینی برابر یا کمتر از {value}", "Scheduled": "برنامه‌ریزی‌شده", "Past due": "زمان گذشته",
  "Not specified": "مشخص نشده", "Unnamed plant": "گیاه بدون نام", "Save Changes": "ذخیره تغییرات", "Saving...": "در حال ذخیره…",
  "Reported": "گزارش‌شده", "Report": "گزارش", "Model": "مدل", "Forecast": "پیش‌بینی", "Latest report": "آخرین گزارش",
  "Latest model estimate": "آخرین برآورد مدل", "Daytime": "روز", "Nighttime": "شب", "Daily forecast low": "کمینه پیش‌بینی روزانه",
  "Daily forecast high": "بیشینه پیش‌بینی روزانه", "Available night forecast low": "کمینه پیش‌بینی شب", "Air temperature": "دمای هوا",
  "Refresh": "تازه‌سازی", "Checking…": "در حال بررسی…", "Valid time": "زمان اعتبار", "Report time": "زمان گزارش", "Current conditions": "شرایط فعلی",
  "Your locations": "موقعیت‌های شما", "Farm locations": "موقعیت مزرعه‌ها", "Weather at your farms and gardens": "هواشناسی مزرعه‌ها و باغ‌های شما",
  "Location needed": "موقعیت لازم است", "Open local forecast": "مشاهده پیش‌بینی محلی", "Save changes": "ذخیره تغییرات",
  "AI Powered": "مجهز به هوش مصنوعی", "Weather Intelligence": "هواشناسی هوشمند", "Smart Irrigation": "آبیاری هوشمند",
  "GPS Farm Management": "مدیریت مزرعه روی نقشه", "AI Crop Assistant": "دستیار هوشمند کشت", "Hyper-local Weather": "هواشناسی محلی",
  "AI Crop Recommendations": "پیشنهادهای هوشمند کشت", "Sensor Monitoring": "پایش حسگرها", "Crop Planning": "برنامه‌ریزی کشت",
  "AI optimizes irrigation schedules for every farm.": "هوش مصنوعی برنامه آبیاری هر مزرعه را بهینه می‌کند.",
  "Hyper-local weather forecasts based on farm location.": "پیش‌بینی هوا بر اساس موقعیت مزرعه.",
  "Receive intelligent recommendations to improve yield.": "پیشنهادهای هوشمند برای بهبود عملکرد محصول دریافت کنید.",
  "Animations paused by your reduced-motion setting": "انیمیشن با تنظیم کاهش حرکت متوقف شده است", "Enable weather animations": "فعال کردن انیمیشن هواشناسی",
  "Pause weather animations": "توقف انیمیشن هواشناسی", "Chance —": "احتمال —", "Change": "تغییر",
  "Choose the exact position of your farm on the map": "موقعیت دقیق مزرعه را روی نقشه انتخاب کنید", "Close details": "بستن جزئیات", "Close map": "بستن نقشه",
  "Daily forecast unavailable": "پیش‌بینی روزانه در دسترس نیست", "Farm Information": "اطلاعات مزرعه", "Farm Name": "نام مزرعه",
  "Farm overview": "نمای کلی مزرعه", "Forecast day": "روز پیش‌بینی", "Garden Information": "اطلاعات باغ", "Garden Name": "نام باغ",
  "Irrigation control": "کنترل آبیاری", "Loading weather": "دریافت هواشناسی", "Location selected": "موقعیت انتخاب شد",
  "Model valid": "اعتبار مدل", "My farms and gardens": "مزرعه‌ها و باغ‌های من", "Open Map": "باز کردن نقشه",
  "Open farm locations": "نمایش موقعیت مزرعه‌ها", "Open-Meteo · Model estimate": "Open-Meteo · برآورد مدل",
  "Plant / Tree Types": "انواع گیاه یا درخت", "Primary Crop": "محصول اصلی", "Refresh weather": "تازه‌سازی هواشناسی",
  "Remove plant": "حذف گیاه", "Select exact location": "انتخاب موقعیت دقیق", "Select farm": "انتخاب مزرعه", "Select irrigation type": "انتخاب روش آبیاری",
  "Total Plants / Trees": "تعداد کل گیاهان و درخت‌ها", "Unable to load this farm's weather right now.": "هواشناسی این مزرعه اکنون قابل دریافت نیست.",
  "Weather measurement": "پارامتر هواشناسی", "Weather navigation": "پیمایش هواشناسی", "Your farms": "مزرعه‌های شما",
  "e.g. 250": "مثلاً ۲۵۰", "e.g. 4": "مثلاً ۴", "e.g. Forage Corn": "مثلاً ذرت علوفه‌ای",
  "e.g. Late-blooming Persian walnut": "مثلاً گردوی دیرگل ایرانی", "e.g. North Field": "مثلاً زمین شمالی",
  "e.g. Qazvin, Iran": "مثلاً قزوین، ایران", "e.g. Walnut Garden": "مثلاً باغ گردو", "farm": "مزرعه", "garden": "باغ",
  "item": "مورد", "items": "مورد", "model estimate": "برآورد مدل", "provider report": "گزارش منبع",
  ". The provider does not specify this reading's accumulation period, so it is not used as today's total.": "؛ منبع بازه تجمع این مقدار را مشخص نکرده، بنابراین این عدد مجموع بارش امروز محسوب نمی‌شود.",
  "Surface": "سطحی", "Drip": "قطره‌ای", "Sprinkler": "بارانی", "Other": "سایر",
  "Water flows across the soil surface": "آب روی سطح خاک جاری می‌شود", "Water is delivered directly to plant roots": "آب مستقیم به ریشه گیاه می‌رسد",
  "Water is distributed through sprinklers": "آب با آب‌پاش‌ها توزیع می‌شود", "Another irrigation method": "روش دیگر آبیاری",
  "Field Start Moisture": "رطوبت ابتدای زمین", "Field End Moisture": "رطوبت انتهای زمین",
  "Hourly forecast amounts. Today's total is the provider's forecast for the full local calendar day; it is not a rain-gauge measurement or the amount that has already fallen.": "مقادیر، پیش‌بینی ساعتی‌اند. مجموع امروز، پیش‌بینی منبع برای تمام روز محلی است؛ نه اندازه‌گیری باران‌سنج و نه بارش رخ‌داده تا این لحظه.",
  "Sustained wind and short gusts can differ substantially. Check both when planning field work; these forecasts do not establish safe spraying conditions.": "سرعت باد پایدار و تندبادهای کوتاه می‌توانند متفاوت باشند. هنگام برنامه‌ریزی کار مزرعه هر دو را بررسی کنید؛ این پیش‌بینی به‌تنهایی ایمنی سم‌پاشی را مشخص نمی‌کند.",
  "Air temperature and feels-like temperature. The main Now reading is the provider's latest report; this chart contains hourly forecasts, including earlier forecast hours.": "دمای هوا و دمای احساسی. عدد «اکنون» آخرین گزارش منبع است؛ این نمودار پیش‌بینی ساعتی، شامل ساعت‌های گذشته، را نشان می‌دهد.",
  "Relative humidity of the air. Soil moisture and leaf wetness need separate measurements and are not inferred from this percentage.": "رطوبت نسبی هوا. رطوبت خاک و خیسی برگ به اندازه‌گیری جداگانه نیاز دارند و از این درصد نتیجه‌گیری نمی‌شوند.",
  "The temperature at which air becomes saturated. A small gap between air temperature and dew point can support condensation; it does not confirm wet leaves.": "دمایی که هوا در آن اشباع می‌شود. اختلاف کم دما و نقطه شبنم می‌تواند به میعان کمک کند؛ اما خیسی برگ را تأیید نمی‌کند.",
  "Forecast air temperature with a {value} reference. Ground frost can occur at a different air temperature; sensitivity depends on the crop and its growth stage.": "پیش‌بینی دمای هوا با مرجع {value}. یخ‌زدگی زمین ممکن است در دمای هوای دیگری رخ دهد؛ حساسیت به نوع محصول و مرحله رشد بستگی دارد.",
  "Sunrise and sunset at this location, shown in the farm's local time. Daylight duration is not the number of hours of direct sunshine.": "طلوع و غروب در موقعیت مزرعه به وقت محلی. طول روز با تعداد ساعت‌های تابش مستقیم خورشید متفاوت است.",
  "Atmospheric pressure as reported by the selected provider. The chart shows the forecast trend, not a measured pressure history.": "فشار هوا طبق گزارش منبع انتخاب‌شده. نمودار روند پیش‌بینی فشار را نشان می‌دهد، نه تاریخچه اندازه‌گیری‌شده.",
  "The forecast fraction of sky covered by cloud. Cloud cover alone does not measure the sunlight reaching a crop.": "درصد پیش‌بینی‌شده آسمان پوشیده از ابر. پوشش ابر به‌تنهایی مقدار نور رسیده به محصول را مشخص نمی‌کند.",
  "H:": "ب:", "L:": "ک:", "{count} saved locations": "{count} موقعیت ذخیره‌شده", "Open chart and details": "مشاهده نمودار و جزئیات",
  "No {metric} forecast is available for this day.": "پیش‌بینی {metric} برای این روز در دسترس نیست.",
  " over the previous {minutes} minutes.": " در {minutes} دقیقه گذشته.",
  "Name is required.": "نام لازم است.", "Area is required.": "مساحت لازم است.", "Area must be greater than 0.": "مساحت باید بیشتر از صفر باشد.",
  "Exact location is required.": "موقعیت دقیق لازم است.", "Automation not connected": "خودکارسازی متصل نیست", "Controller offline": "کنترل‌کننده آفلاین",
  "Controller error": "خطای کنترل‌کننده", "Control unavailable": "کنترل در دسترس نیست", "Controller is offline": "کنترل‌کننده آفلاین است",
  "Controller needs attention": "کنترل‌کننده به بررسی نیاز دارد", "Remote control unavailable": "کنترل از راه دور در دسترس نیست",
  "Irrigation in progress": "آبیاری در حال انجام است", "Controller ready": "کنترل‌کننده آماده است",
  "Remote irrigation control is temporarily unavailable. Check the controller power and network connection.": "کنترل آبیاری از راه دور موقتاً در دسترس نیست؛ برق و اتصال شبکه کنترل‌کننده را بررسی کنید.",
  "AgroMind cannot communicate with the irrigation controller. Remote commands are disabled until the connection is restored.": "ارتباط با کنترل‌کننده آبیاری برقرار نیست. فرمان‌های از راه دور تا بازگشت اتصال غیرفعال‌اند.",
  "The controller connection exists, but remote irrigation commands are not available yet.": "کنترل‌کننده متصل است، اما فرمان‌های آبیاری از راه دور هنوز آماده نیستند.",
  "No irrigation controller is connected to {farm}. Connect a compatible controller to enable remote start and stop.": "کنترل‌کننده‌ای به {farm} متصل نیست. برای شروع و توقف از راه دور، کنترل‌کننده سازگار متصل کنید.",
  "{farm} is currently being irrigated.": "آبیاری {farm} در حال انجام است.",
  "{farm} is connected and ready for remote irrigation control.": "{farm} متصل و آماده کنترل آبیاری از راه دور است.",
};
