export const LANDING_PERSIAN: Record<string, string> = {
  "How it works": "نحوهٔ کار",
  "Farm preview": "پیش‌نمایش مزرعه",
  "Manage your farms, review local forecasts and plan irrigation in one place.": "مزرعه‌هایتان را مدیریت کنید، پیش‌بینی آب‌وهوای منطقه را ببینید و آبیاری را در یک جا برنامه‌ریزی کنید.",
  "Preview the app": "پیش‌نمایش اپ",
  "Farm management & weather": "مدیریت مزرعه و آب‌وهوا",
  "Farm-local forecasts": "پیش‌بینی آب‌وهوای مزرعه",
  "Irrigation planning": "برنامه‌ریزی آبیاری",
  "AI · Coming soon": "هوش مصنوعی · به‌زودی",
  "Illustrative preview": "پیش‌نمایش نمونه",
  "Sample data": "داده‌های نمونه",
  "View farm-local forecasts with clearly labeled sources and update times.": "پیش‌بینی آب‌وهوای مزرعه را با منبع و زمان به‌روزرسانی مشخص ببینید.",
  "Plan when your fields need water.": "زمان آبیاری مزرعه‌ها را برنامه‌ریزی کنید.",
  "Save irrigation dates and durations for each farm. Automatic watering and device control are not yet available.": "تاریخ و مدت آبیاری هر مزرعه را ذخیره کنید. آبیاری خودکار و کنترل تجهیزات هنوز فعال نیست.",
  "AI recommendations are planned. The assistant does not generate advice yet.": "توصیه‌های هوش مصنوعی در برنامهٔ توسعه هستند. دستیار هنوز توصیه‌ای تولید نمی‌کند.",
  "Farm management, weather and irrigation planning are available today. AI and connected devices are planned.": "مدیریت مزرعه، آب‌وهوا و برنامه‌ریزی آبیاری اکنون در دسترس‌اند. هوش مصنوعی و اتصال تجهیزات در برنامهٔ توسعه هستند.",
  "Available now": "اکنون در دسترس",
  "Illustrative preview · Sample data": "پیش‌نمایش نمایشی · داده‌های نمونه",
  "Example of a planned recommendation": "نمونه‌ای از توصیهٔ قابلیت آینده",
  "Device integration planned": "اتصال تجهیزات در برنامهٔ توسعه",
  "Plan irrigation": "برنامه‌ریزی آبیاری",
  "Recommendations planned": "توصیه‌ها در برنامهٔ توسعه",
  "Start with farm records, local weather and irrigation schedules. Sensor connections and AI recommendations are planned additions.": "با اطلاعات مزرعه، آب‌وهوای منطقه و برنامهٔ آبیاری شروع کنید. اتصال حسگرها و توصیه‌های هوش مصنوعی در برنامهٔ توسعه هستند.",
  "Sample farm overview": "نمای کلی مزرعهٔ نمونه",
  "Explore a preview of the planned connected farm experience. Sensor readings and AI advice shown here are sample data.": "پیش‌نمایشی از مزرعهٔ متصل در برنامهٔ توسعه را ببینید. مقادیر حسگرها و توصیه‌های هوش مصنوعی این بخش داده‌های نمونه‌اند.",
};
