export const PERSIAN: Record<string, string> = {
  "Settings": "تنظیمات", "App Settings": "تنظیمات برنامه", "Back to dashboard": "بازگشت به داشبورد",
  "Your region. Your language. Your way of measuring.": "منطقه، زبان و واحدها؛ مطابق انتخاب شما.",
  "Saved on this device": "در این دستگاه ذخیره شد",
  "Saved for this tab only. Browser storage is unavailable.": "فقط در این تب ذخیره شد؛ فضای ذخیره‌سازی مرورگر در دسترس نیست.",
  "Region & language": "منطقه و زبان", "Region": "منطقه", "Website language": "زبان سایت",
  "Follow region": "مطابق منطقه", "Language changes text and reading direction, independently of units.": "زبان، متن و جهت صفحه را تغییر می‌دهد و از واحدها مستقل است.",
  "Changing region updates automatic preferences. Your custom choices stay the same.": "تغییر منطقه فقط تنظیمات خودکار را تغییر می‌دهد؛ انتخاب‌های دستی شما حفظ می‌شوند.",
  "English and Persian are available. Other regional languages currently use English.": "زبان‌های فارسی و انگلیسی در دسترس‌اند. برای دیگر زبان‌های منطقه‌ای فعلاً انگلیسی نمایش داده می‌شود.",
  "Measurement units": "واحدهای اندازه‌گیری", "Temperature": "دما", "Land area": "مساحت زمین", "Distance": "فاصله",
  "Length & plant spacing": "طول و فاصله کاشت", "Wind speed": "سرعت باد", "Rainfall": "بارش", "Water volume": "حجم آب", "Pressure": "فشار هوا",
  "Reset units to regional defaults": "بازگرداندن واحدها به پیش‌فرض منطقه",
  "Date & time": "تاریخ و ساعت", "Calendar": "تقویم", "Gregorian": "میلادی", "Persian": "هجری شمسی", "Buddhist": "بودایی",
  "Time format": "قالب ساعت", "12-hour": "۱۲ ساعته", "24-hour": "۲۴ ساعته", "Numerals": "شکل اعداد",
  "Weather times always follow the farm's time zone. Changing region never moves a farm.": "ساعت‌های هواشناسی همیشه به وقت محلی مزرعه‌اند. تغییر منطقه، موقعیت مزرعه را تغییر نمی‌دهد.",
  "Appearance & motion": "ظاهر و حرکت", "Theme": "پوسته", "Light": "روشن", "Dark": "تیره", "System": "مطابق دستگاه",
  "Weather animations": "انیمیشن‌های هواشناسی", "Paused by your device's reduced-motion setting.": "با تنظیم کاهش حرکت دستگاه شما متوقف شده است.",
  "Rain, clouds and other weather effects.": "حرکت باران، ابرها و دیگر جلوه‌های هواشناسی.",
  "Live preview": "پیش‌نمایش زنده", "Sample farm · Not live data": "مزرعه نمونه · داده‌ها زنده نیستند",
  "Date": "تاریخ", "Time": "ساعت", "Applies to farm forms, weather, charts and irrigation. Stored farm measurements stay unchanged.": "در فرم مزرعه، هواشناسی، نمودارها و آبیاری اعمال می‌شود. مقادیر ذخیره‌شده مزرعه تغییر نمی‌کنند.",
  "Make AgroMind yours": "AgroMind را برای خودتان تنظیم کنید",
  "Choose your region for local examples and default units. Language and units can be changed separately in Settings.": "منطقه را برای مثال‌های محلی و واحدهای پیش‌فرض انتخاب کنید. زبان و واحدها در تنظیمات جداگانه قابل تغییرند.",
  "Suggested from your location. Confirm below.": "منطقه بر اساس موقعیت پیشنهاد شد؛ پایین تأیید کنید.",
  "Choose your region manually.": "منطقه خود را دستی انتخاب کنید.",
  "Location unavailable. You can choose your region below.": "موقعیت در دسترس نیست؛ می‌توانید منطقه را دستی انتخاب کنید.",
  "Detecting region…": "در حال یافتن منطقه…", "Suggest from my location": "پیشنهاد بر اساس موقعیت من", "Continue": "ادامه",
  "Iran": "ایران", "United States": "آمریکا", "United Kingdom": "بریتانیا", "China": "چین", "Japan": "ژاپن", "Thailand": "تایلند",
  "Celsius (°C)": "سلسیوس (°C)", "Fahrenheit (°F)": "فارنهایت (°F)", "Square metres (m²)": "متر مربع (m²)",
  "Hectares (ha)": "هکتار (ha)", "Acres (ac)": "ایکر (ac)", "Kilometres (km)": "کیلومتر (km)", "Miles (mi)": "مایل (mi)",
  "Metres (m)": "متر (m)", "Feet (ft)": "فوت (ft)", "Kilometres per hour (km/h)": "کیلومتر بر ساعت (km/h)", "Miles per hour (mph)": "مایل بر ساعت (mph)",
  "Millimetres (mm)": "میلی‌متر (mm)", "Inches (in)": "اینچ (in)", "Litres (L)": "لیتر (L)", "US gallons (gal)": "گالن آمریکا (gal)",
  "Hectopascals (hPa)": "هکتوپاسکال (hPa)", "Inches of mercury (inHg)": "اینچ جیوه (inHg)",
  "Qazvin, Iran": "قزوین، ایران", "Fresno, California": "فرزنو، کالیفرنیا", "Norfolk, UK": "نورفک، بریتانیا",
  "Chengdu, China": "چنگدو، چین", "Niigata, Japan": "نیگاتا، ژاپن", "Chiang Mai, Thailand": "چیانگ‌مای، تایلند",
  "Corn": "ذرت", "Almonds": "بادام", "Wheat": "گندم", "Rice": "برنج",
  "Weather": "هواشناسی", "Dashboard": "داشبورد", "Farms": "مزرعه‌ها", "My Farms": "مزرعه‌های من", "My Farm": "مزرعه من",
  "Farm": "مزرعه", "Garden": "باغ", "Add farm": "افزودن مزرعه", "Add Farm": "افزودن مزرعه", "Add New Farm": "افزودن مزرعه",
  "Humidity": "رطوبت", "Soil Moisture": "رطوبت خاک", "AI Status": "وضعیت هوش مصنوعی", "Sunny": "آفتابی",
  "Irrigation": "آبیاری", "Sensors": "حسگرها", "Overview": "نمای کلی", "Analytics": "تحلیل‌ها", "Sign In": "ورود", "Get Started": "شروع کنید",
  "Hourly forecast": "پیش‌بینی ساعتی", "Daily forecast": "پیش‌بینی روزانه", "Field outlook": "وضعیت پیش روی مزرعه",
  "Chart": "نمودار", "Now": "اکنون", "Last report": "آخرین گزارش", "Today": "امروز", "Tomorrow": "فردا",
  "Precipitation": "بارش", "Wind & gusts": "باد و تندباد", "Night low": "کمینه شب", "Dew point": "نقطه شبنم", "Daylight": "روشنایی روز",
  "Today's total forecast": "مجموع بارش پیش‌بینی‌شده امروز", "Current report": "گزارش فعلی", "Model estimate": "برآورد مدل",
  "Conditions for your field": "شرایط مزرعه شما", "Tap a card for hourly details": "برای جزئیات ساعتی روی کارت بزنید",
  "Current reading unavailable": "داده فعلی در دسترس نیست", "Daily range unavailable": "دامنه روزانه در دسترس نیست", "Chance unavailable": "احتمال در دسترس نیست",
  "Air humidity, not soil moisture": "رطوبت هوا؛ متفاوت با رطوبت خاک", "Next night · Forecast": "شب آینده · پیش‌بینی", "Rest of night · Forecast": "ادامه شب · پیش‌بینی",
  "Night forecast unavailable": "پیش‌بینی شب در دسترس نیست", "Open the night temperature chart": "مشاهده نمودار دمای شب", "Compare dew point with air temperature": "نقطه شبنم را با دمای هوا مقایسه کنید",
  "Open the hourly pressure trend": "مشاهده روند ساعتی فشار", "Feels like {value}": "دمای احساسی {value}", "Today's forecast {low} to {high}": "پیش‌بینی امروز از {low} تا {high}",
  "From {direction} · {report}": "از {direction} · {report}", "Gusts {value} now": "تندباد فعلی {value}",
  "Relative humidity · {report}": "رطوبت نسبی · {report}", "Air temperature forecast at or below {value}": "پیش‌بینی دمای هوا برابر یا کمتر از {value}",
  "Sunrise {time}": "طلوع {time}", "Sunset {time} · Local time": "غروب {time} · وقت محلی", "{hours}h {minutes}m": "{hours} ساعت و {minutes} دقیقه",
  "{count}-day forecast": "پیش‌بینی {count} روزه", "All times are local to this farm.": "همه ساعت‌ها به وقت محلی این مزرعه‌اند.",
  "Peak forecast gust": "بیشترین تندباد پیش‌بینی‌شده", "Next night · forecast low": "شب آینده · کمینه پیش‌بینی", "Rest of night · forecast low": "ادامه شب · کمینه پیش‌بینی",
  "Forecast humidity range": "دامنه رطوبت پیش‌بینی‌شده", "Rain timing & amounts": "زمان و مقدار بارش",
  "Wind and humidity use available forecasts within the next 24 hours. Check rain timing before adjusting irrigation; soil moisture and crop needs are separate inputs.": "باد و رطوبت از پیش‌بینی ۲۴ ساعت آینده‌اند. پیش از تنظیم آبیاری زمان بارش را بررسی کنید؛ رطوبت خاک و نیاز گیاه نیز باید جداگانه در نظر گرفته شوند.",
  "Daily forecast is unavailable.": "پیش‌بینی روزانه در دسترس نیست.",
  "Rain is forecast around {time}. Peak gusts reach {wind}.": "بارش حوالی {time} پیش‌بینی می‌شود. بیشترین تندباد {wind} است.",
  "No rain in the available hourly forecast. Peak gusts reach {wind}.": "در پیش‌بینی ساعتی موجود بارشی دیده نمی‌شود. بیشترین تندباد {wind} است.",
  "Hourly forecast is unavailable.": "پیش‌بینی ساعتی در دسترس نیست.",
};
