export const WEATHER_PERSIAN: Record<string, string> = {
  "sunny": "آفتابی", "clear": "صاف", "mainly clear": "عمدتاً صاف", "partly cloudy": "نیمه‌ابری", "cloudy": "ابری", "overcast": "تمام‌ابری",
  "mist": "مه رقیق", "fog": "مه", "freezing fog": "مه یخ‌زن", "rime fog": "مه یخ‌زن", "dust": "گردوغبار", "haze": "غبار",
  "patchy rain nearby": "باران پراکنده در اطراف", "patchy rain possible": "احتمال باران پراکنده", "patchy snow nearby": "برف پراکنده در اطراف",
  "patchy snow possible": "احتمال برف پراکنده", "patchy sleet nearby": "برف‌آب پراکنده در اطراف", "patchy sleet possible": "احتمال برف‌آب پراکنده",
  "patchy freezing drizzle nearby": "نم‌باران یخ‌زن پراکنده در اطراف", "patchy freezing drizzle possible": "احتمال نم‌باران یخ‌زن پراکنده",
  "thundery outbreaks in nearby": "رعدوبرق در اطراف", "thundery outbreaks possible": "احتمال رعدوبرق", "blowing snow": "برف همراه با باد", "blizzard": "کولاک",
  "patchy light drizzle": "نم‌باران سبک پراکنده", "light drizzle": "نم‌باران سبک", "moderate drizzle": "نم‌باران متوسط", "heavy drizzle": "نم‌باران شدید",
  "freezing drizzle": "نم‌باران یخ‌زن", "light freezing drizzle": "نم‌باران یخ‌زن سبک", "heavy freezing drizzle": "نم‌باران یخ‌زن شدید",
  "patchy light rain": "باران سبک پراکنده", "light rain": "باران سبک", "moderate rain at times": "باران متوسط در بعضی ساعت‌ها", "moderate rain": "باران متوسط",
  "heavy rain at times": "باران شدید در بعضی ساعت‌ها", "heavy rain": "باران شدید", "light freezing rain": "باران یخ‌زن سبک", "heavy freezing rain": "باران یخ‌زن شدید",
  "moderate or heavy freezing rain": "باران یخ‌زن متوسط یا شدید", "light sleet": "برف‌آب سبک", "moderate or heavy sleet": "برف‌آب متوسط یا شدید",
  "patchy light snow": "برف سبک پراکنده", "light snow": "برف سبک", "patchy moderate snow": "برف متوسط پراکنده", "moderate snow": "برف متوسط",
  "patchy heavy snow": "برف شدید پراکنده", "heavy snow": "برف شدید", "ice pellets": "دانه‌های یخ", "snow grains": "برف دانه‌ای",
  "light rain shower": "رگبار سبک", "light rain showers": "رگبار سبک", "moderate rain showers": "رگبار متوسط", "heavy rain showers": "رگبار شدید",
  "moderate or heavy rain shower": "رگبار متوسط یا شدید", "torrential rain shower": "رگبار بسیار شدید",
  "light sleet showers": "رگبار برف‌آب سبک", "moderate or heavy sleet showers": "رگبار برف‌آب متوسط یا شدید",
  "light snow showers": "رگبار برف سبک", "heavy snow showers": "رگبار برف شدید", "moderate or heavy snow showers": "رگبار برف متوسط یا شدید",
  "light showers of ice pellets": "رگبار سبک دانه‌های یخ", "moderate or heavy showers of ice pellets": "رگبار متوسط یا شدید دانه‌های یخ",
  "patchy light rain in area with thunder": "باران سبک پراکنده همراه با رعدوبرق", "patchy light rain with thunder": "باران سبک پراکنده همراه با رعدوبرق",
  "moderate or heavy rain in area with thunder": "باران متوسط یا شدید همراه با رعدوبرق", "moderate or heavy rain with thunder": "باران متوسط یا شدید همراه با رعدوبرق",
  "patchy light snow in area with thunder": "برف سبک پراکنده همراه با رعدوبرق", "patchy light snow with thunder": "برف سبک پراکنده همراه با رعدوبرق",
  "moderate or heavy snow in area with thunder": "برف متوسط یا شدید همراه با رعدوبرق", "moderate or heavy snow with thunder": "برف متوسط یا شدید همراه با رعدوبرق",
  "thunderstorm": "توفان تندری", "thunderstorm with slight hail": "توفان تندری با تگرگ سبک", "thunderstorm with heavy hail": "توفان تندری با تگرگ شدید",
  "unknown": "نامشخص", "unknown weather": "هوای نامشخص",
};
