export const WORKSPACE_PERSIAN: Record<string, string> = {
  "Give your farm a location": "موقعیت مزرعه را مشخص کنید",
  "Irrigation is on your calendar": "آبیاری در برنامهٔ شما ثبت شده",
  "Irrigation scheduled": "آبیاری برنامه‌ریزی شده",
  "Plan your next irrigation": "برای آبیاری بعدی برنامه‌ریزی کنید",
  "Review schedule": "بررسی برنامه",
  Home: "خانه",
  Assistant: "دستیار",
  Preferences: "تنظیمات",
  "Help & Support": "راهنما و پشتیبانی",
  "About AgroMind": "دربارهٔ اگرو مایند",
  "Sign in": "ورود",
  "A place for everything you grow.": "مزرعه‌ها و باغ‌هایتان را یکجا مدیریت کنید.",
  "Add a farm or garden to keep weather, crops and irrigation together.":
    "مزرعه یا باغ خود را اضافه کنید تا آب‌وهوا، محصول و آبیاری را یکجا ببینید.",
  "Controls & sensors": "کنترل و حسگرها",
  "Skip to content": "رفتن به محتوای اصلی",
  "Loading…": "در حال بارگذاری…",
  "Simple tools for everything you grow": "ابزارهای ساده برای هر آنچه می‌کارید",
  "AgroMind brings your farms, local weather and irrigation plans into one calm, clear space.":
    "اگرو مایند مزرعه‌ها، آب‌وهوای محلی و برنامه‌های آبیاری شما را در فضایی ساده و روشن کنار هم می‌آورد.",
  "Visit AgroMind": "وب‌سایت اگرو مایند",
  "AgroMind Assistant": "دستیار اگرو مایند",
  "A little help for the questions that grow with your farm.":
    "راهنمای شما برای سؤال‌های روزمره مزرعه.",
  "What would you like to explore?": "درباره چه چیزی سؤال دارید؟",
  "Personal advice is coming soon. You can prepare a question below.":
    "دستیار شخصی به‌زودی فعال می‌شود. فعلاً می‌توانید سؤال‌تان را اینجا آماده کنید.",
  "Your question": "سؤال شما",
  "Ask about your farm…": "دربارهٔ مزرعهٔ خود بپرسید…",
  "Chat is not available yet. Your draft stays in this page.":
    "گفت‌وگو هنوز فعال نیست. متن شما فقط تا زمانی که در این صفحه هستید باقی می‌ماند.",
  "Send message": "ارسال پیام",
  "A clear view of your growing day.": "وضعیت امروز مزرعه، در یک نگاه.",
  "Your farm today": "امروز در مزرعهٔ شما",
  "Local weather starts with the right place.":
    "برای آب‌وهوای محلی، موقعیت مزرعه را مشخص کنید.",
  "Choose a time and keep your next watering easy to find.":
    "زمانی انتخاب کنید تا نوبت بعدی آبیاری همیشه مشخص باشد.",
  "At a glance": "در یک نگاه",
  "Crop not added yet": "هنوز محصولی ثبت نشده",
  "Soil readings will appear when a sensor is connected.":
    "پس از اتصال حسگر، اطلاعات خاک اینجا نمایش داده می‌شود.",
  "Edit crop details": "ویرایش اطلاعات محصول",
  "Your crop information is saved. Personal advice will be available in a future update.":
    "اطلاعات محصول ذخیره شده است. راهنمایی متناسب با مزرعه شما به‌زودی اضافه می‌شود.",
  "Set a time that works for your farm.":
    "زمان مناسب مزرعهٔ خود را انتخاب کنید.",
  "Crop insights": "اطلاعات محصول",
  "View crop details": "مشاهدهٔ اطلاعات محصول",
  "{count} plants and trees": "{count} گیاه و درخت",
  "Your crop information, in one place.": "اطلاعات محصول شما، در یک نگاه.",
  "View sensors": "مشاهدهٔ حسگرها",
  "Farm navigation": "بخش‌های مزرعه",
  "Main navigation": "بخش‌های اصلی",
  "A little clarity. A better growing day.":
    "همراه شما در کارهای روزمره مزرعه.",
  "Opening page…": "در حال باز کردن صفحه…",
  "Forecast details & refresh": "جزئیات پیش‌بینی و به‌روزرسانی",
  "Your details and contact information": "مشخصات و اطلاعات تماس شما",
  "Authenticators, recovery and sessions": "احراز هویت، بازیابی و نشست‌ها",
  "Your plan and what is included": "طرح اشتراک و امکانات شما",
  "Your farms and available limits": "میزان استفاده و ظرفیت باقی‌مانده",
  "Language, units and appearance": "زبان، واحدها و ظاهر",
  "Find your next step": "پاسخ سؤال‌های رایج و راه‌های ارتباط",
  "How do I get started?": "از کجا شروع کنم؟",
  "Add a farm or garden, choose its location, then open its overview for weather and irrigation.":
    "مزرعه یا باغی اضافه و موقعیت آن را انتخاب کنید؛ سپس در نمای کلی، آب‌وهوا و آبیاری را ببینید.",
  "How can I protect my account?": "چطور از حسابم محافظت کنم؟",
  "Open Security to add an authenticator and an independent backup. Keep the backup on a separate device.":
    "در بخش امنیت، یک احرازگر و یک احرازگر پشتیبان مستقل اضافه کنید. پشتیبان را روی دستگاهی جداگانه نگه دارید.",
  "Where are my language and units?": "زبان و واحدها را کجا تغییر دهم؟",
  "Preferences lets you choose language, region, measurement units, calendar and appearance.":
    "در تنظیمات می‌توانید زبان، منطقه، واحدها، تقویم و ظاهر برنامه را تغییر دهید.",
  "Irrigation advice": "راهنمای آبیاری",
  "Crop health": "سلامت محصول",
  "Weather outlook": "پیش‌بینی هوا",
  "Pest / disease help": "راهنمای آفت و بیماری",
  "How can I plan irrigation for my farm?":
    "چطور برای آبیاری مزرعه‌ام برنامه‌ریزی کنم؟",
  "What should I check to understand my crop's health?":
    "برای اطمینان از سلامت محصولم چه چیزهایی را بررسی کنم؟",
  "How could the weather affect my farm?":
    "آب‌وهوا چه تأثیری بر مزرعه‌ام دارد؟",
  "What details should I collect about a pest or disease?":
    "برای شناسایی آفت یا بیماری چه اطلاعاتی جمع‌آوری کنم؟",

  "Your plan's farm limit is reached": "ظرفیت مزرعه‌های این طرح تکمیل شده",
  "You've reached the farm limit for your current plan.": "به سقف تعداد مزرعه‌های طرح فعلی رسیده‌اید. برای بررسی ظرفیت، اشتراک خود را ببینید.",
  "Current plan: up to {limit} farms.": "ظرفیت طرح فعلی: {limit} مزرعه",
  "Next irrigation": "نوبت بعدی آبیاری",
  "Soil monitoring": "وضعیت خاک",
  "View forecast": "مشاهده پیش‌بینی",
  "Question ready. You can edit it below.": "سؤال آماده است؛ می‌توانید متنش را ویرایش کنید.",
  "No sensor is connected to this farm. Sensor connections are not available yet; you can still check weather and plan irrigation.": "هنوز حسگری به این مزرعه متصل نیست و امکان اتصال حسگر فعلاً فعال نشده است. می‌توانید هواشناسی و برنامه آبیاری را در نمای کلی ببینید.",
  "Getting started": "شروع کار",
  "Account & Security": "حساب کاربری و امنیت",
  "Language & Settings": "زبان و تنظیمات",
  "What can I do from Home?": "در صفحه خانه چه چیزهایی می‌بینم؟",
  "Choose your active farm to see its weather, saved irrigation schedule and crop details together.": "مزرعه موردنظر را انتخاب کنید تا هواشناسی، برنامه آبیاری و اطلاعات محصول آن را یکجا ببینید.",
  "How do I edit a farm or garden?": "چطور اطلاعات مزرعه یا باغ را تغییر دهم؟",
  "Open your farm, choose Edit, then save your changes. You can update its name, location, area, crop and irrigation method.": "صفحه مزرعه را باز کنید و «ویرایش» را بزنید. نام، موقعیت، مساحت، محصول و روش آبیاری را تغییر دهید و ذخیره کنید.",
  "Why can't I add another farm?": "چرا نمی‌توانم مزرعه دیگری اضافه کنم؟",
  "Your plan sets the number of farms you can add. Check your subscription for the current limit.": "تعداد مزرعه‌ها به طرح اشتراک شما بستگی دارد. ظرفیت فعلی را در بخش اشتراک ببینید.",
  "How do I plan irrigation?": "چطور برنامه آبیاری ثبت کنم؟",
  "Open Irrigation from your farm and choose a date, start time and duration. Your saved schedule stays with that farm.": "در صفحه مزرعه وارد بخش آبیاری شوید و تاریخ، ساعت شروع و مدت آبیاری را انتخاب کنید. برنامه برای همان مزرعه ذخیره می‌شود.",
  "Choose a farm": "انتخاب مزرعه",
  "Does a saved schedule control my pump?": "ثبت برنامه، پمپ آب را روشن می‌کند؟",
  "A saved schedule is a plan. Equipment control needs a connected controller; saving a schedule does not confirm that watering has started.": "با ذخیره برنامه فقط زمان آبیاری ثبت می‌شود. روشن‌کردن تجهیزات به دستگاه کنترل متصل نیاز دارد؛ ذخیره برنامه به معنی شروع آبیاری نیست.",
  "Why is my farm's weather unavailable?": "چرا هواشناسی مزرعه نمایش داده نمی‌شود؟",
  "Check your internet connection and the farm's map location, then try refreshing the forecast.": "اتصال اینترنت و موقعیت مزرعه روی نقشه را بررسی کنید، سپس پیش‌بینی را دوباره دریافت کنید.",
  "Why can rainfall readings differ?": "چرا مقدار بارش در بخش‌های مختلف متفاوت است؟",
  "A current reading and a daily forecast cover different periods. Open the forecast details to check the time and source of each reading.": "مقدار لحظه‌ای و پیش‌بینی روزانه برای بازه‌های زمانی متفاوت‌اند. در جزئیات پیش‌بینی، زمان و منبع هر مقدار را ببینید.",
  "Where can I see my plan and usage?": "طرح و میزان استفاده‌ام را کجا ببینم؟",
  "Subscription shows your plan and its limits. Usage shows your saved farms and schedules.": "در بخش اشتراک، طرح و ظرفیت آن را ببینید. تعداد مزرعه‌ها و برنامه‌های ذخیره‌شده هم در بخش میزان استفاده مشخص است.",
  "Can I use the Persian calendar?": "می‌توانم از تقویم شمسی استفاده کنم؟",
  "Choose the Persian calendar in Settings. Dates change for display; your saved irrigation schedule stays the same.": "در تنظیمات، تقویم شمسی را انتخاب کنید. فقط نمایش تاریخ تغییر می‌کند و زمان برنامه‌های آبیاری همان می‌ماند.",
  "Find a quick answer and get back to your farm.": "پاسخ سؤال‌تان را پیدا کنید و راحت‌تر به کار مزرعه برسید.",
  "Quick help": "راهنمای سریع",
  "Need more help?": "هنوز به کمک نیاز دارید؟",
  "Support contact options are being prepared. The guides above are available now.": "راه‌های ارتباط با پشتیبانی هنوز فعال نشده‌اند. فعلاً می‌توانید از راهنماهای بالا کمک بگیرید.",
  "Submit Support Ticket": "ثبت درخواست پشتیبانی",
  "Email Support": "ایمیل به پشتیبانی",
  "An official support email has not been published yet.": "ایمیل رسمی پشتیبانی هنوز اعلام نشده است.",
  "Ticket submission is not available yet. You can prepare a draft here, but it will not be sent or saved when you leave.": "ارسال درخواست هنوز فعال نیست. می‌توانید متن را اینجا آماده کنید؛ این متن ارسال نمی‌شود و با خروج از صفحه از بین می‌رود.",
  "Subject": "موضوع",
  "Category": "دسته‌بندی",
  "Description": "توضیحات",
  "Submit": "ارسال درخواست",
  "Choose a support category": "انتخاب دسته‌بندی",
  "Farm management": "مدیریت مزرعه",
  "Billing / Subscription": "پرداخت و اشتراک",
  "Bug report": "گزارش مشکل",
  "Tell us what happened and what you expected. Do not include passwords or verification codes.": "بنویسید چه اتفاقی افتاد و انتظار داشتید چه شود. رمز عبور یا کد تأیید را وارد نکنید.",
  "Enter a subject with at least 3 characters.": "موضوع را در حداقل ۳ حرف بنویسید.",
  "Keep the subject under 120 characters.": "موضوع نباید بیشتر از ۱۲۰ کاراکتر باشد.",
  "Choose a support category.": "دسته‌بندی درخواست را انتخاب کنید.",
  "Describe the issue in at least 20 characters.": "مشکل را کمی بیشتر توضیح دهید؛ حداقل ۲۰ کاراکتر بنویسید.",
  "Keep the description under 4,000 characters.": "توضیحات نباید بیشتر از ۴۰۰۰ کاراکتر باشد.",
  "Our mission": "هدف ما",
  "Make everyday farm decisions easier to understand, for everyone who grows.": "می‌خواهیم تصمیم‌های روزمره مزرعه برای همه کسانی که می‌کارند، ساده‌تر و روشن‌تر شود.",
  "Built around your farm": "همراه کارهای مزرعه",
  "App version": "نسخه برنامه",
  "Keep your farms, gardens and crops organized.": "اطلاعات مزرعه‌ها، باغ‌ها و محصولات را یکجا مدیریت کنید.",
  "Weather intelligence": "هواشناسی مزرعه",
  "See local conditions and forecasts for your farm.": "وضعیت فعلی هوا و پیش‌بینی محل مزرعه را ببینید.",
  "Irrigation planning": "برنامه‌ریزی آبیاری",
  "Keep your next watering date, time and duration in view.": "تاریخ، ساعت و مدت نوبت بعدی آبیاری را مشخص کنید.",
  "Connected soil readings are planned for a future update.": "نمایش اطلاعات خاک از حسگرها در به‌روزرسانی‌های آینده اضافه می‌شود.",
  "AI assistance": "دستیار هوشمند",
  "Personal farm advice is planned for a future update.": "راهنمایی متناسب با مزرعه شما در به‌روزرسانی‌های آینده اضافه می‌شود.",
  "View only access": "دسترسی فقط برای مشاهده",
  "Your role does not allow editing this farm or garden.": "نقش شما اجازه ویرایش این مزرعه یا باغ را نمی‌دهد.",
  "Your role allows you to view irrigation details but not change the schedule.": "نقش شما اجازه مشاهده جزئیات آبیاری را می‌دهد، اما نمی‌توانید برنامه را تغییر دهید.",
  "Your role does not allow this change.": "نقش شما اجازه انجام این تغییر را نمی‌دهد.",
  "Only the farm owner can make this change.": "فقط مالک مزرعه می‌تواند این تغییر را انجام دهد.",
  "Your team member limit has been reached.": "ظرفیت اعضای تیم طرح شما تکمیل شده است.",
  "Manager": "مدیر",
  "Worker": "همکار",
  "Viewer": "مشاهده‌گر",
  "Team": "تیم",
  "Invite people and manage farm access": "دعوت اعضا و مدیریت دسترسی به مزرعه‌ها",
  "Farm team": "تیم مزرعه",
  "Invite people to individual farms and choose exactly what they can change.": "افراد را به مزرعه‌های مشخص دعوت کنید و دقیقاً تعیین کنید چه چیزهایی را بتوانند تغییر دهند.",
  "Team seats": "ظرفیت تیم",
  "A person uses one team seat even when they have access to more than one of your farms.": "هر شخص حتی با دسترسی به چند مزرعه شما فقط یک ظرفیت تیم اشغال می‌کند.",
  "Team collaboration is not included in your current plan.": "امکان همکاری تیمی در طرح فعلی شما فعال نیست.",
  "Check your subscription to see the team member limit.": "برای مشاهده ظرفیت اعضای تیم، اشتراک خود را بررسی کنید.",
  "View subscription": "مشاهده اشتراک",
  "Invite a team member": "دعوت عضو تیم",
  "The invitation is valid for 7 days and only the invited email address can accept it.": "دعوت‌نامه ۷ روز اعتبار دارد و فقط همان آدرس ایمیل دعوت‌شده می‌تواند آن را بپذیرد.",
  "Role": "نقش",
  "Can view and edit the farm and manage irrigation.": "می‌تواند مزرعه را مشاهده و ویرایش کند و برنامه آبیاری را مدیریت کند.",
  "Can view the farm and manage irrigation.": "می‌تواند مزرعه را مشاهده کند و برنامه آبیاری را مدیریت کند.",
  "Can view farm and irrigation details only.": "فقط می‌تواند اطلاعات مزرعه و آبیاری را مشاهده کند.",
  "Send invitation": "ارسال دعوت‌نامه",
  "Your team member limit has been reached. Remove an active or pending seat before inviting someone new.": "ظرفیت اعضای تیم تکمیل شده است. پیش از دعوت فرد جدید، یک عضو فعال یا دعوت‌نامه در انتظار را حذف کنید.",
  "Invitation sent.": "دعوت‌نامه ارسال شد.",
  "Active team members": "اعضای فعال تیم",
  "Roles are assigned separately for each farm.": "نقش هر فرد برای هر مزرعه به‌صورت جداگانه تعیین می‌شود.",
  "Farm access": "دسترسی مزرعه",
  "Role updated.": "نقش به‌روزرسانی شد.",
  "Remove access": "حذف دسترسی",
  "Access removed.": "دسترسی حذف شد.",
  "No active team members yet.": "هنوز عضو فعالی در تیم وجود ندارد.",
  "Pending invitations": "دعوت‌نامه‌های در انتظار",
  "Pending invitations reserve a team seat until they expire or are cancelled.": "دعوت‌نامه‌های در انتظار تا زمان انقضا یا لغو، یک ظرفیت تیم را رزرو می‌کنند.",
  "Expires": "انقضا",
  "Cancel invitation": "لغو دعوت‌نامه",
  "Invitation cancelled.": "دعوت‌نامه لغو شد.",
  "No pending invitations.": "دعوت‌نامه‌ای در انتظار نیست.",
  "Check the email, farm and role.": "ایمیل، مزرعه و نقش را بررسی کنید.",
  "You already own this farm and cannot invite yourself.": "شما مالک این مزرعه هستید و نمی‌توانید خودتان را دعوت کنید.",
  "This person already has access to the selected farm.": "این شخص از قبل به مزرعه انتخاب‌شده دسترسی دارد.",
  "Enter a valid email address.": "یک آدرس ایمیل معتبر وارد کنید.",
  "Choose a valid team role.": "یک نقش معتبر برای تیم انتخاب کنید.",
  "The selected farm is no longer available.": "مزرعه انتخاب‌شده دیگر در دسترس نیست.",
  "Sign in with the email address that received this invitation.": "با همان آدرس ایمیلی وارد شوید که دعوت‌نامه را دریافت کرده است.",
  "This invitation has expired. Ask the farm owner for a new invite.": "این دعوت‌نامه منقضی شده است. از مالک مزرعه بخواهید دعوت جدیدی ارسال کند.",
  "This invitation is invalid or no longer available.": "این دعوت‌نامه نامعتبر است یا دیگر در دسترس نیست.",
  "Only the farm owner can manage team access.": "فقط مالک مزرعه می‌تواند دسترسی اعضای تیم را مدیریت کند.",
  "Complete two-step verification before managing team access.": "پیش از مدیریت دسترسی تیم، تأیید دومرحله‌ای را کامل کنید.",
  "The invitation email could not be sent. Please try again.": "ایمیل دعوت‌نامه ارسال نشد. دوباره تلاش کنید.",
  "Team access could not be updated. Please try again.": "دسترسی تیم به‌روزرسانی نشد. دوباره تلاش کنید.",
  "The team member could not be removed.": "حذف عضو تیم انجام نشد.",
  "You're invited to collaborate in AgroMind": "برای همکاری در اگرو مایند دعوت شده‌اید",
  "A farm has been shared with you": "یک مزرعه با شما به اشتراک گذاشته شده",
  "You've been invited to help manage {farm} with the {role} role.": "برای همکاری در مدیریت {farm} با نقش {role} دعوت شده‌اید.",
  "Review invitation": "بررسی دعوت‌نامه",
  "This invitation expires in 7 days and can only be accepted by the email address that received it.": "این دعوت‌نامه ۷ روز اعتبار دارد و فقط همان آدرس ایمیلی که آن را دریافت کرده می‌تواند قبولش کند.",
  "If you were not expecting this invitation, you can safely ignore this email.": "اگر منتظر چنین دعوتی نبودید، می‌توانید این ایمیل را نادیده بگیرید.",
  "Invitation declined": "دعوت‌نامه رد شد",
  "Farm invitation": "دعوت به مزرعه",
  "No farm access was added to your account.": "هیچ دسترسی جدیدی به مزرعه به حساب شما اضافه نشد.",
  "Go to dashboard": "رفتن به داشبورد",
  "Review this invitation while signed in with the email address that received it.": "این دعوت‌نامه را با همان آدرس ایمیلی بررسی کنید که دعوت را دریافت کرده است.",
  "Signed in as": "وارد شده با",
  "AgroMind verifies the invited email, invitation expiry and team capacity before access is added.": "اگرو مایند پیش از افزودن دسترسی، ایمیل دعوت‌شده، اعتبار دعوت‌نامه و ظرفیت تیم را بررسی می‌کند.",
  "This invitation could not be accepted. Please try again.": "پذیرش دعوت‌نامه انجام نشد. دوباره تلاش کنید.",
  "This invitation could not be declined. Please try again.": "رد کردن دعوت‌نامه انجام نشد. دوباره تلاش کنید.",
  "Decline": "رد کردن",
  "Accept invitation": "پذیرفتن دعوت",
  "Invitation unavailable": "دعوت‌نامه در دسترس نیست",
  "Go to AgroMind": "رفتن به اگرو مایند",
  "Resend invitation": "ارسال دوباره دعوت‌نامه",
  "Invitation resent.": "دعوت‌نامه دوباره ارسال شد.",
  "Wait a moment before resending this invitation.": "کمی صبر کنید و سپس دعوت‌نامه را دوباره ارسال کنید.",
};
